# Generated by Django 4.2.7 on 2026-02-10 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='prorab',
            field=models.ForeignKey(help_text='Foreman (prorab) assigned to this project', limit_choices_to={'role': 'foreman'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projectassignment',
            index=models.Index(fields=['project', 'prorab'], name='projects_pr_project_a4f91d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectassignment',
            index=models.Index(fields=['prorab'], name='projects_pr_prorab__26d0d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectassignment',
            unique_together={('project', 'prorab')},
        ),
    ]
