# Generated by Django 4.2.7 on 2026-02-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actualexpense',
            new_name='expenses_ac_finance_bd3093_idx',
            old_name='expenses_act_finance_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='actualexpense',
            new_name='expenses_ac_categor_fde96a_idx',
            old_name='expenses_act_catego_def456_idx',
        ),
        migrations.RenameIndex(
            model_name='actualexpense',
            new_name='expenses_ac_spent_a_05ad4e_idx',
            old_name='expenses_act_spent__ghi789_idx',
        ),
    ]
