# Generated by Django 4.2.7 on 2026-03-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_actualexpense_account'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actualexpense',
            new_name='expenses_ac_month_p_de6e9e_idx',
            old_name='expenses_ac_month_p_7a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='actualexpense',
            new_name='expenses_ac_account_b1873a_idx',
            old_name='expenses_ac_account_idx',
        ),
    ]
