# Generated by Django 4.2.7 on 2026-03-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_rename_expenses_ac_month_p_7a1b2c_idx_expenses_ac_month_p_de6e9e_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='actualexpense',
            index=models.Index(fields=['account', 'spent_at'], name='expenses_ac_account_778e7f_idx'),
        ),
    ]
