# Generated by Django 4.2.7 on 2026-04-16 14:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_actualexpense_currency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actualexpense',
            new_name='expenses_ac_currenc_c76105_idx',
            old_name='expenses_ac_currenc_idx',
        ),
        migrations.RenameIndex(
            model_name='actualexpense',
            new_name='expenses_ac_account_94e1d9_idx',
            old_name='expenses_ac_acc_cur_spnt_idx',
        ),
        migrations.AlterField(
            model_name='actualexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount spent', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
