# Generated by Django 4.2.7 on 2026-02-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_kind', models.CharField(choices=[('project', 'Project'), ('office', 'Office'), ('charity', 'Charity')], help_text='Type of fund: project, office, or charity', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('closed', 'Closed')], default='open', help_text='Status of the finance period', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month_period__month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Income amount', max_digits=12)),
                ('received_at', models.DateField(help_text='Date when money was received')),
                ('comment', models.TextField(help_text='Required comment for this income entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
    ]
