# Generated by Django 4.2.7 on 2026-02-10 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
        ('projects', '0001_initial'),
        ('budgeting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeentry',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this income entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_income_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='finance_period',
            field=models.ForeignKey(help_text='Finance period for this income entry', on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to='finance.financeperiod'),
        ),
        migrations.AddField(
            model_name='financeperiod',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this finance period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financeperiod',
            name='month_period',
            field=models.ForeignKey(help_text='Month period for this finance period', on_delete=django.db.models.deletion.CASCADE, related_name='finance_periods', to='budgeting.monthperiod'),
        ),
        migrations.AddField(
            model_name='financeperiod',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project (required if fund_kind=project, null otherwise)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_periods', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='incomeentry',
            index=models.Index(fields=['finance_period', 'received_at'], name='finance_inc_finance_944739_idx'),
        ),
        migrations.AddIndex(
            model_name='incomeentry',
            index=models.Index(fields=['received_at'], name='finance_inc_receive_a7ce3c_idx'),
        ),
        migrations.AddIndex(
            model_name='financeperiod',
            index=models.Index(fields=['month_period', 'fund_kind'], name='finance_fin_month_p_a2628e_idx'),
        ),
        migrations.AddIndex(
            model_name='financeperiod',
            index=models.Index(fields=['fund_kind', 'status'], name='finance_fin_fund_ki_1f4b30_idx'),
        ),
        migrations.AddIndex(
            model_name='financeperiod',
            index=models.Index(fields=['project', 'month_period'], name='finance_fin_project_452862_idx'),
        ),
    ]
