# Generated by Django 4.2.7 on 2026-02-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Planned income amount', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the income source', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this income source is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='incomesource',
            index=models.Index(fields=['is_active'], name='finance_inc_is_acti_80b61a_idx'),
        ),
        migrations.AddField(
            model_name='incomeplan',
            name='period',
            field=models.ForeignKey(help_text='Finance period for this income plan', on_delete=django.db.models.deletion.CASCADE, related_name='income_plans', to='finance.financeperiod'),
        ),
        migrations.AddField(
            model_name='incomeplan',
            name='source',
            field=models.ForeignKey(help_text='Income source for this plan', on_delete=django.db.models.deletion.CASCADE, related_name='income_plans', to='finance.incomesource'),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Income source for this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_entries', to='finance.incomesource'),
        ),
        migrations.AddIndex(
            model_name='incomeplan',
            index=models.Index(fields=['period'], name='finance_inc_period__6c69c8_idx'),
        ),
        migrations.AddIndex(
            model_name='incomeplan',
            index=models.Index(fields=['source'], name='finance_inc_source__15c7a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='incomeplan',
            constraint=models.UniqueConstraint(fields=('period', 'source'), name='unique_income_plan_period_source'),
        ),
    ]
