# Generated by Django 4.2.7 on 2026-02-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_finance_period_unique_constraint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incomeentry',
            index=models.Index(fields=['source'], name='finance_inc_source__ff268c_idx'),
        ),
    ]
