# Generated by Django 4.2.7 on 2026-03-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_transfer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incomeentry',
            new_name='finance_inc_account_64e805_idx',
            old_name='finance_inc_account_idx',
        ),
        migrations.RenameIndex(
            model_name='transfer',
            new_name='finance_tra_transfe_cbcdc5_idx',
            old_name='finance_tra_transfe_idx',
        ),
        migrations.RenameIndex(
            model_name='transfer',
            new_name='finance_tra_source__48b556_idx',
            old_name='finance_tra_source__idx',
        ),
    ]
