# Generated by Django 4.2.7 on 2026-03-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_rename_finance_inc_account_idx_finance_inc_account_64e805_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLedgerLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank')], help_text='Logical money account (CASH or BANK) used for locking', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Account ledger lock',
                'verbose_name_plural': 'Account ledger locks',
                'indexes': [models.Index(fields=['account'], name='finance_acc_account_fd7fa9_idx')],
            },
        ),
    ]
