# Generated by Django 4.2.7 on 2026-03-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_accountledgerlock'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incomeentry',
            index=models.Index(fields=['account', 'received_at'], name='finance_inc_account_a11800_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['source_account', 'transferred_at'], name='finance_tra_source__62efb9_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['destination_account', 'transferred_at'], name='finance_tra_destina_695d3d_idx'),
        ),
    ]
