# Generated by Django 4.2.7 on 2026-04-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_incomeentry_currency_transfer_currency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incomeentry',
            new_name='finance_inc_currenc_6ab0e1_idx',
            old_name='finance_inc_currenc_idx',
        ),
        migrations.RenameIndex(
            model_name='incomeentry',
            new_name='finance_inc_account_0478d8_idx',
            old_name='finance_inc_acc_cur_rcvd_idx',
        ),
        migrations.RenameIndex(
            model_name='transfer',
            new_name='finance_tra_currenc_40a649_idx',
            old_name='finance_tr_currenc_idx',
        ),
    ]
