# Generated by Django 4.2.7 on 2026-04-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_currencyexchange'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='currencyexchange',
            new_name='finance_cur_exchang_4aefec_idx',
            old_name='finance_cur_exchang_idx1',
        ),
        migrations.RenameIndex(
            model_name='currencyexchange',
            new_name='finance_cur_source__922fc8_idx',
            old_name='finance_cur_src_idx',
        ),
        migrations.RenameIndex(
            model_name='currencyexchange',
            new_name='finance_cur_destina_402f44_idx',
            old_name='finance_cur_dst_idx',
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
