# Generated by Django 4.2.7 on 2026-02-10 11:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_spent', models.DecimalField(decimal_places=2, help_text='Amount spent', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(blank=True, help_text='Optional comment')),
                ('spent_at', models.DateField(default=django.utils.timezone.localdate, help_text='Date when expense was incurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-spent_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_planned', models.DecimalField(decimal_places=2, help_text='Planned amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.TextField(blank=True, help_text='Optional note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category__name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('OFFICE', 'Office'), ('PROJECT', 'Project'), ('CHARITY', 'Charity')], help_text='OFFICE or PROJECT (must match root_category.scope)', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period__month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Format: YYYY-MM (e.g., 2024-01)', max_length=7, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month', 'status'], name='budgeting_m_month_397910_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('project', 'Project'), ('office', 'Office'), ('charity', 'Charity')], default='project', help_text='Scope: project, office, or charity', max_length=20)),
                ('kind', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], default='EXPENSE', help_text='Kind: EXPENSE or INCOME', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for tree structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budgeting.expensecategory')),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPlanSummaryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(help_text='Summary comment for the budget plan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_comment', to='budgeting.budgetplan')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
