# Generated by Django 4.2.7 on 2026-02-04 13:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('OFFICE', 'Office'), ('PROJECT', 'Project')], help_text='OFFICE or PROJECT', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period__month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Format: YYYY-MM (e.g., 2024-01)', max_length=7, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month', 'status'], name='budgeting_m_month_397910_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('project', 'Project'), ('office', 'Office')], default='project', help_text='Scope: project or office', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for tree structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budgeting.expensecategory')),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPlanSummaryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(help_text='Summary comment for the budget plan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_comment', to='budgeting.budgetplan')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_budget_summary_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to='budgeting.monthperiod'),
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Required when scope=PROJECT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to='projects.project'),
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_planned', models.DecimalField(decimal_places=2, help_text='Planned amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.TextField(blank=True, help_text='Optional note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Must be a leaf category', on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='budgeting.expensecategory')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budgeting.budgetplan')),
            ],
            options={
                'ordering': ['category__name'],
            },
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['scope', 'is_active'], name='budgeting_e_scope_395b24_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['parent'], name='budgeting_e_parent__1bf418_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetplan',
            index=models.Index(fields=['period', 'scope', 'project'], name='budgeting_b_period__326f03_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetplan',
            index=models.Index(fields=['status'], name='budgeting_b_status_79d073_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['plan', 'category'], name='budgeting_b_plan_id_714f89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetline',
            unique_together={('plan', 'category')},
        ),
    ]
