# Generated by Django 4.2.7 on 2026-02-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetplan',
            name='root_category',
            field=models.ForeignKey(
                help_text='Root category (must have parent=None)',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='root_budget_plans',
                to='budgeting.expensecategory',
                null=False,
                blank=False,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='budgetplan',
            unique_together={('period', 'root_category', 'project')},
        ),
        migrations.AddIndex(
            model_name='budgetplan',
            index=models.Index(fields=['period', 'root_category', 'project'], name='budgeting_b_period__root_cat_idx'),
        ),
    ]

