# Generated by Django 4.2.7 on 2026-02-10 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetplansummarycomment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_budget_summary_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to='budgeting.monthperiod'),
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Required when scope=PROJECT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to='projects.project'),
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='root_category',
            field=models.ForeignKey(help_text='Root category (must have parent=None)', on_delete=django.db.models.deletion.PROTECT, related_name='root_budget_plans', to='budgeting.expensecategory'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='category',
            field=models.ForeignKey(help_text='Must be a leaf category', on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='budgeting.expensecategory'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budgeting.budgetplan'),
        ),
        migrations.AddField(
            model_name='budgetexpense',
            name='category',
            field=models.ForeignKey(help_text='Expense category (must be leaf and active)', on_delete=django.db.models.deletion.PROTECT, related_name='budget_expenses', to='budgeting.expensecategory'),
        ),
        migrations.AddField(
            model_name='budgetexpense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetexpense',
            name='plan',
            field=models.ForeignKey(help_text='Budget plan this expense belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budgeting.budgetplan'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['scope', 'is_active'], name='budgeting_e_scope_395b24_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['kind', 'is_active'], name='budgeting_e_kind_1d8a93_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['parent'], name='budgeting_e_parent__1bf418_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetplan',
            index=models.Index(fields=['period', 'scope', 'project'], name='budgeting_b_period__326f03_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetplan',
            index=models.Index(fields=['status'], name='budgeting_b_status_79d073_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetplan',
            index=models.Index(fields=['period', 'root_category', 'project'], name='budgeting_b_period__3073da_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetplan',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'PROJECT')), fields=('period', 'project'), name='unique_project_period'),
        ),
        migrations.AddConstraint(
            model_name='budgetplan',
            constraint=models.UniqueConstraint(condition=models.Q(('scope__in', ['OFFICE', 'CHARITY'])), fields=('period', 'scope'), name='unique_office_charity_period'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['plan', 'category'], name='budgeting_b_plan_id_714f89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetline',
            unique_together={('plan', 'category')},
        ),
        migrations.AddIndex(
            model_name='budgetexpense',
            index=models.Index(fields=['plan', 'category'], name='budgeting_b_plan_id_934bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetexpense',
            index=models.Index(fields=['spent_at'], name='budgeting_b_spent_a_9077d1_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetexpense',
            index=models.Index(fields=['plan', 'spent_at'], name='budgeting_b_plan_id_268a7c_idx'),
        ),
    ]
