# Generated by Django 4.2.7 on 2026-02-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0004_fix_unique_constraint_and_validation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='budgetplan',
            new_name='budgeting_b_period__3073da_idx',
            old_name='budgeting_b_period__root_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='budgeting_e_kind_1d8a93_idx',
            old_name='budgeting_e_kind_is_a_idx',
        ),
        migrations.AlterField(
            model_name='budgetplan',
            name='scope',
            field=models.CharField(choices=[('OFFICE', 'Office'), ('PROJECT', 'Project'), ('CHARITY', 'Charity')], help_text='OFFICE or PROJECT (must match root_category.scope)', max_length=20),
        ),
    ]
