# Generated by Django 4.2.7 on 2026-02-06 06:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgeting', '0005_rename_budgeting_b_period__root_cat_idx_budgeting_b_period__3073da_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_spent', models.DecimalField(decimal_places=2, help_text='Amount spent', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(blank=True, help_text='Optional comment')),
                ('spent_at', models.DateField(default=django.utils.timezone.localdate, help_text='Date when expense was incurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Expense category (must be leaf and active)', on_delete=django.db.models.deletion.PROTECT, related_name='budget_expenses', to='budgeting.expensecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_expenses', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(help_text='Budget plan this expense belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budgeting.budgetplan')),
            ],
            options={
                'ordering': ['-spent_at', '-created_at'],
                'indexes': [models.Index(fields=['plan', 'category'], name='budgeting_b_plan_id_934bf5_idx'), models.Index(fields=['spent_at'], name='budgeting_b_spent_a_9077d1_idx'), models.Index(fields=['plan', 'spent_at'], name='budgeting_b_plan_id_268a7c_idx')],
            },
        ),
    ]
