# Generated by Django 4.2.7 on 2026-03-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('budgeting', '0005_remove_budget_plan_root_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetplan',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional; not used for plan key (all scopes keyed by period + scope only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='budgetplan',
            name='scope',
            field=models.CharField(choices=[('OFFICE', 'Office'), ('PROJECT', 'Project'), ('CHARITY', 'Charity')], help_text='OFFICE, PROJECT, or CHARITY', max_length=20),
        ),
    ]
