# Generated by Django 4.2.7 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0006_alter_budgetplan_project_alter_budgetplan_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='is_system_root',
            field=models.BooleanField(default=False),
        ),
    ]

