# Generated by Django 4.2.7 on 2026-03-26

from django.db import migrations, models
from django.db.models import Q
from django.db.models.functions import Lower, Trim


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0007_expensecategory_is_system_root'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(
                fields=('scope',),
                condition=Q(parent__isnull=True, is_active=True),
                name='uniq_active_root_per_scope',
            ),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(
                'parent',
                'scope',
                Lower(Trim('name')),
                condition=Q(parent__isnull=False),
                name='uniq_child_name_per_parent_norm',
            ),
        ),
    ]

