# Generated by Django 4.2.7 on 2026-04-23 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarterCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.PositiveSmallIntegerField()),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('vin', models.CharField(blank=True, max_length=32)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True)),
                ('has_tech_passport', models.BooleanField(default=False)),
                ('received_by_dover', models.BooleanField(default=False)),
                ('received_from_name', models.CharField(max_length=120)),
                ('received_from_phone', models.CharField(blank=True, max_length=20)),
                ('apartment_ref', models.CharField(blank=True, max_length=120)),
                ('agreed_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('agreed_currency', models.CharField(choices=[('KGS', 'KGS'), ('USD', 'USD')], default='USD', max_length=3)),
                ('received_at', models.DateField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('SOLD', 'Sold')], default='RECEIVED', max_length=20)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sold_currency', models.CharField(blank=True, choices=[('KGS', 'KGS'), ('USD', 'USD')], max_length=3, null=True)),
                ('sold_to_name', models.CharField(blank=True, max_length=120)),
                ('sold_to_phone', models.CharField(blank=True, max_length=20)),
                ('sold_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_barter_cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['status'], name='barter_cars_status_817712_idx'), models.Index(fields=['is_active'], name='barter_cars_is_acti_e60a77_idx'), models.Index(fields=['received_at'], name='barter_cars_receive_88969d_idx')],
            },
        ),
    ]
