# Generated by Django 4.2.7 on 2026-02-04 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Format: YYYY-MM (e.g., 2024-01)', max_length=7)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, help_text='Comments from approval/rejection')),
                ('limit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly limit amount for this period', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plan_periods', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_periods', to='projects.project')),
            ],
            options={
                'ordering': ['-period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProrabPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount of all plan items', max_digits=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, help_text='Comments from approval/rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prorab_plans', to='planning.planperiod')),
                ('prorab', models.ForeignKey(help_text='Foreman (prorab) who owns this plan', limit_choices_to={'role': 'foreman'}, on_delete=django.db.models.deletion.CASCADE, related_name='prorab_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plan_items', to=settings.AUTH_USER_MODEL)),
                ('plan_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='planning.planperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProrabPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this item', max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.prorabplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plan', 'created_at'], name='planning_pr_plan_id_920e37_idx'), models.Index(fields=['category'], name='planning_pr_categor_1cc02e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prorabplan',
            index=models.Index(fields=['period', 'prorab'], name='planning_pr_period__91f89e_idx'),
        ),
        migrations.AddIndex(
            model_name='prorabplan',
            index=models.Index(fields=['status'], name='planning_pr_status_a2dd93_idx'),
        ),
        migrations.AddIndex(
            model_name='prorabplan',
            index=models.Index(fields=['prorab', 'status'], name='planning_pr_prorab__55b8c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prorabplan',
            unique_together={('period', 'prorab')},
        ),
        migrations.AddIndex(
            model_name='planperiod',
            index=models.Index(fields=['project', 'period'], name='planning_pl_project_8f68b6_idx'),
        ),
        migrations.AddIndex(
            model_name='planperiod',
            index=models.Index(fields=['status'], name='planning_pl_status_5fdd3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planperiod',
            unique_together={('project', 'period')},
        ),
        migrations.AddIndex(
            model_name='planitem',
            index=models.Index(fields=['plan_period', 'created_at'], name='planning_pl_plan_pe_1f03ec_idx'),
        ),
        migrations.AddIndex(
            model_name='planitem',
            index=models.Index(fields=['category'], name='planning_pl_categor_a07def_idx'),
        ),
    ]
