# Generated by Django 4.2.7 on 2026-02-10 11:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Expense name (e.g., бетон)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount spent in KGS', max_digits=12)),
                ('spent_at', models.DateField(help_text='Date when money was spent')),
                ('comment', models.TextField(help_text='Required comment for every expense')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-spent_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_at', models.DateField(help_text='Date when expense was incurred')),
                ('name', models.CharField(help_text='Expense name', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in KGS', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('comment', models.TextField(blank=True, help_text='Optional comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-spent_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_kind', models.CharField(choices=[('project', 'Project'), ('office', 'Office'), ('charity', 'Charity')], help_text='Type of fund: project, office, or charity', max_length=20)),
                ('period', models.CharField(help_text='Format: YYYY-MM (e.g., 2024-01)', max_length=7)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, help_text='Comments from approval/rejection')),
                ('limit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly limit amount for this period', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProrabPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount of all plan items', max_digits=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, help_text='Comments from approval/rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProrabPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Material name (e.g., бетон)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in KGS', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Expense category (must be subcategory with parent != null, scope = project)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prorab_plan_items', to='budgeting.expensecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
