# Generated by Django 4.2.7 on 2026-02-10 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0001_initial'),
        ('budgeting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prorabplanitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prorab_plan_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prorabplanitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.prorabplan'),
        ),
        migrations.AddField(
            model_name='prorabplan',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prorab_plans', to='planning.planperiod'),
        ),
        migrations.AddField(
            model_name='prorabplan',
            name='prorab',
            field=models.ForeignKey(help_text='Foreman (prorab) who owns this plan', limit_choices_to={'role': 'foreman'}, on_delete=django.db.models.deletion.CASCADE, related_name='prorab_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planperiod',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plan_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planperiod',
            name='month_period',
            field=models.ForeignKey(blank=True, help_text='Link to canonical MonthPeriod for this period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_periods', to='budgeting.monthperiod'),
        ),
        migrations.AddField(
            model_name='planperiod',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project (required if fund_kind=project, null otherwise)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_periods', to='projects.project'),
        ),
        migrations.AddField(
            model_name='planitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plan_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planitem',
            name='plan_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='planning.planperiod'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Expense category (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='budgeting.expensecategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='plan_period',
            field=models.ForeignKey(help_text='Plan period this expense belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='planning.planperiod'),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Expense category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_expenses', to='budgeting.expensecategory'),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='created_by',
            field=models.ForeignKey(help_text='Admin who created this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_actual_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='finance_period',
            field=models.ForeignKey(help_text='Finance period (required)', on_delete=django.db.models.deletion.CASCADE, related_name='actual_expenses', to='finance.financeperiod'),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Optional period link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_expenses', to='planning.planperiod'),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='prorab_plan',
            field=models.ForeignKey(blank=True, help_text='Optional link to prorab plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_expenses', to='planning.prorabplan'),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='prorab_plan_item',
            field=models.ForeignKey(blank=True, help_text='Optional link to specific prorab plan item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_expenses', to='planning.prorabplanitem'),
        ),
        migrations.AddIndex(
            model_name='prorabplanitem',
            index=models.Index(fields=['plan', 'created_at'], name='planning_pr_plan_id_920e37_idx'),
        ),
        migrations.AddIndex(
            model_name='prorabplanitem',
            index=models.Index(fields=['category'], name='planning_pr_categor_31daee_idx'),
        ),
        migrations.AddIndex(
            model_name='prorabplan',
            index=models.Index(fields=['period', 'prorab'], name='planning_pr_period__91f89e_idx'),
        ),
        migrations.AddIndex(
            model_name='prorabplan',
            index=models.Index(fields=['status'], name='planning_pr_status_a2dd93_idx'),
        ),
        migrations.AddIndex(
            model_name='prorabplan',
            index=models.Index(fields=['prorab', 'status'], name='planning_pr_prorab__55b8c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prorabplan',
            unique_together={('period', 'prorab')},
        ),
        migrations.AddIndex(
            model_name='planperiod',
            index=models.Index(fields=['project', 'period'], name='planning_pl_project_8f68b6_idx'),
        ),
        migrations.AddIndex(
            model_name='planperiod',
            index=models.Index(fields=['status'], name='planning_pl_status_5fdd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='planperiod',
            index=models.Index(fields=['fund_kind', 'period'], name='planning_pl_fund_ki_07e54c_idx'),
        ),
        migrations.AddConstraint(
            model_name='planperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('fund_kind', 'project')), fields=('project', 'period'), name='planning_unique_project_period'),
        ),
        migrations.AddConstraint(
            model_name='planperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('fund_kind__in', ['office', 'charity'])), fields=('fund_kind', 'period'), name='planning_unique_office_charity_period'),
        ),
        migrations.AddIndex(
            model_name='planitem',
            index=models.Index(fields=['plan_period', 'created_at'], name='planning_pl_plan_pe_1f03ec_idx'),
        ),
        migrations.AddIndex(
            model_name='planitem',
            index=models.Index(fields=['category'], name='planning_pl_categor_a07def_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['plan_period', 'spent_at'], name='planning_ex_plan_pe_f3f6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['spent_at'], name='planning_ex_spent_a_3fc782_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='planning_ex_categor_504e07_idx'),
        ),
        migrations.AddIndex(
            model_name='actualexpense',
            index=models.Index(fields=['finance_period', 'spent_at'], name='planning_ac_finance_6cdcb0_idx'),
        ),
        migrations.AddIndex(
            model_name='actualexpense',
            index=models.Index(fields=['prorab_plan', 'spent_at'], name='planning_ac_prorab__b44c09_idx'),
        ),
        migrations.AddIndex(
            model_name='actualexpense',
            index=models.Index(fields=['period', 'spent_at'], name='planning_ac_period__a6dafc_idx'),
        ),
    ]
