# Generated by Django 4.2.7 on 2026-02-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_remove_name_from_expense'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='planning_ex_plan_it_829e84_idx',
            old_name='planning_ex_plan_it_idx',
        ),
    ]
