# Generated by Django 4.2.7 on 2026-02-04 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('budgeting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0004_make_name_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Expense name (e.g., бетон)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount spent in KGS', max_digits=12)),
                ('spent_at', models.DateField(help_text='Date when money was spent')),
                ('comment', models.TextField(help_text='Required comment for every expense')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-spent_at', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='prorabplanitem',
            name='planning_pr_categor_1cc02e_idx',
        ),
        migrations.RemoveField(
            model_name='prorabplanitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='prorabplanitem',
            name='note',
        ),
        migrations.RemoveField(
            model_name='prorabplanitem',
            name='title',
        ),
        migrations.AddField(
            model_name='prorabplanitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prorab_plan_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prorabplanitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in KGS', max_digits=12),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Expense category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_expenses', to='budgeting.expensecategory'),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='created_by',
            field=models.ForeignKey(help_text='Admin who created this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_actual_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Optional period link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_expenses', to='planning.planperiod'),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='project',
            field=models.ForeignKey(help_text='Project (can be Office project)', on_delete=django.db.models.deletion.CASCADE, related_name='actual_expenses', to='projects.project'),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='prorab_plan',
            field=models.ForeignKey(blank=True, help_text='Optional link to prorab plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_expenses', to='planning.prorabplan'),
        ),
        migrations.AddField(
            model_name='actualexpense',
            name='prorab_plan_item',
            field=models.ForeignKey(blank=True, help_text='Optional link to specific prorab plan item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_expenses', to='planning.prorabplanitem'),
        ),
        migrations.AddIndex(
            model_name='actualexpense',
            index=models.Index(fields=['project', 'spent_at'], name='planning_ac_project_4dc0fe_idx'),
        ),
        migrations.AddIndex(
            model_name='actualexpense',
            index=models.Index(fields=['prorab_plan', 'spent_at'], name='planning_ac_prorab__b44c09_idx'),
        ),
        migrations.AddIndex(
            model_name='actualexpense',
            index=models.Index(fields=['period', 'spent_at'], name='planning_ac_period__a6dafc_idx'),
        ),
    ]
