# Generated by Django 4.2.7 on 2026-02-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0005_rename_budgeting_b_period__root_cat_idx_budgeting_b_period__3073da_idx_and_more'),
        ('planning', '0005_actualexpense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prorabplanitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Expense category (must be subcategory with parent != null, scope = project)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prorab_plan_items', to='budgeting.expensecategory'),
        ),
        migrations.AddIndex(
            model_name='prorabplanitem',
            index=models.Index(fields=['category'], name='planning_pr_categor_31daee_idx'),
        ),
    ]
