# Generated by Django 4.2.7 on 2026-02-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_initial'),
        ('planning', '0006_add_finance_actual_expense_to_expense'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='planitem',
            new_name='planning_pl_categor_c6975c_idx',
            old_name='planning_pl_categor_a07def_idx',
        ),
        migrations.AlterField(
            model_name='planitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Expense category (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='budgeting.expensecategory'),
        ),
        migrations.AlterField(
            model_name='planperiod',
            name='fund_kind',
            field=models.CharField(choices=[('project', 'Project'), ('office', 'Office'), ('charity', 'Charity')], default='office', help_text='Type of fund: project, office, or charity', max_length=20),
        ),
        migrations.AlterField(
            model_name='planperiod',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked'), ('open', 'Open')], default='draft', max_length=20),
        ),
    ]
