# Generated by Django 4.2.7 on 2026-02-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_add_category_fk_field'),
    ]

    operations = [
    ]
