# Generated by Django 4.2.7 on 2026-04-23 12:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_migrate_planitem_category_text_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount spent in KGS', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='planperiod',
            name='limit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly limit amount for this period (informational, not a hard cap)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='prorabplanitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in KGS', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
